services:
  api:
    build: .
    ports:
      - 8080:8080
    restart: on-failure
  prometheus:
    image: prom/prometheus:v2.34.0
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - api
  
  grafana:
    image: grafana/grafana:8.4.5
    ports:
      - 3000:3000
    depends_on:
      - prometheus