scrape_configs:
  - job_name:       'Prometheus'

    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 10s

    static_configs:
      - targets: ['api:8080']
