version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jusan-monitoring-api
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    restart: always

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    restart: always
